#!/usr/bin/env python
import argparse
import string
import md5
import re
import random

def auth():
  pass
  
def main():
  print "**************WELCOME****************\n"
  print "This is the interface for the program\n"
  print "Please enter the email address and the password that you want to use as your identity : "
  iden = raw_input("Email address : ")
  hashp = md5.new(raw_input("Password : ")).digest()
  domain = re.search("@[\w.]+", iden)
  srvr = domain.group()
  srvr = string.lstrip(srvr, '@')
  if srvr == "gmail.com":
    print ("smtp.gmail.com")
  else:
    print("Sorry, " + srvr + " is not supported. Currently only Gmail authentication is available\n")
  print ("Ok, your email address has been authnticated")
  rand = random.random()
  print("DKG has started.........\nDKG has finished. Your share is ")
  print(rand)
  print("\n")
  print("Public key is " + iden)
  
  
if __name__ == "__main__":
  main()
