#!/usr/bin/env python
import argparse
import string
import md5
import re
import random

def auth(username, password):
  parse = re.search("([\w\.]*[\w])[@]([\w.]*[\w])", username)
  uname = parse.group(1)
  domain_name = parse.group(2)
  if domain_name == "gmail.com":
    print ("Authenticating " + username + "..............")
  else:
    print("Sorry, " + domain_name + " is not supported. Currently only Gmail authentication is available\n")
  print ("Hello " + uname + ", your email address has been authnticated\n")
  
def main():
  print "**************WELCOME****************\n"
  print "This is the interface for the program\n"
  print "Please enter the email address and the password that you want to use as your identity : "
  iden = raw_input("Email address : ")
  hashp = md5.new(raw_input("Password : ")).digest()
  auth(iden, hashp)
  rand = random.random()
  print("DKG has started.........\nDKG has finished. Your share is ")
  print(rand)
  print("\n")
  print("Public key is " + iden)
  
  
if __name__ == "__main__":
  main()
